name: "Dev - Build and Test"

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    steps:
        - uses: actions/checkout@v3
        - run: dotnet restore
        - name: Publish
          run: dotnet publish ActionsTest.WebApp -c Release -o artifacts/ActionsTest.WebApp
        - uses: actions/upload-artifact@v3
          with:
            name: build-artifacts
            path: artifacts
            