name: "Dev - Build and Test"

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: dotnet restore
      - name: Publish
        run: dotnet publish ActionsTest.WebApp -c Release -o artifacts/ActionsTest.WebApp
      - name: Zip artifacts
        run: zip -r artifacts.zip artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: build-run-${{ github.run_id }}
          path: artifacts.zip
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-run-${{ github.run_id }}
          path: download
      - name: Display structure of downloaded files
        run: ls -R
