name: "Dev - Build and Test"

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    steps:
        - uses: actions/checkout@v3
        - run: dotnet restore
        - run: dotnet publish ActionsTest.WebApp -c Release -o BuildArtifacts\ActionsTest.WebApp
