name: Slack Notifier
on:
  workflow_run:
    workflows: [Dev - Build and Test]
    types: [completed]

jobs:
  on-failure:
    name: Notify on failure
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.conclusion == 'timed_out'
    steps:
      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo run name: ${{github.event.workflow_run.name}}
          echo conclusiom: ${{github.event.workflow_run.conclusion}}
          echo link: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.event.workflow_run.id}}
        
# curl -X POST -H 'Content-type: application/json' --data '{"text":"GitHub job failure: <${{github.server_url}}/${{github.repository}}/actions/runs/${{github.event.workflow_run.id}}|View Failure>"}'  

      # - uses: ravsamhq/notify-slack-action@v2
      #   with:
      #     status: ${{ github.event.workflow_run.conclusion }}
      #     notification_title: " ${{github.event.workflow_run.name}} - ${{github.event.workflow_run.conclusion}} on ${{github.event.workflow_run.head_branch}} - <${{github.server_url}}/${{github.repository}}/actions/runs/${{github.event.workflow_run.id}}|View Failure>"
      #     message_format: ":fire: *${{github.event.workflow_run.name}}* ${{github.event.workflow_run.conclusion}} in <${{github.server_url}}/${{github.repository}}/${{github.event.workflow_run.head_branch}}|${{github.repository}}>"
      #     footer: "Linked Repo <${{github.server_url}}/${{github.repository}}|${{github.repository}}> | <${{github.server_url}}/${{github.repository}}/actions/runs/${{github.event.workflow_run.id}}|View Failure>"
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.MASTER_PROD_FAIL_SLACK }}